name: pushupking
description: A new Flutter project.

# 이거 추가! (기존 없으면 맨 위에 넣어)
environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

publish_to: 'none'

version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.6
  google_mlkit_pose_detection: ^0.14.0  # ← 업데이트
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.1
  google_sign_in: ^6.2.1
  provider: ^6.1.1